### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 8HoLoN** [ClementNerma/NightOS#1]
Hi,

Why I have you reset the previous NightOS repo ? Have you found a new solution/architecture? And so, have you planning a complete rewrite of NightOS ?

Regards,

**Comment by ClementNerma** [comment]
Hello,

I did not reset the repository, I simply renamed the old one like I did for the previous versions (you can still find it here: https://github.com/ClementNerma/NightOS-v3).

There is indeed a new architecture this time, you can find the long explanations in the [FAQ](https://github.com/ClementNerma/NightOS/blob/master/docs/FAQ.md#how-does-this-project-relates-to-nightos-v1-v2-and-v3). Short version is that now NightOS designed to be a completly custom O.S. instead of a desktop environment based on a Linux kernel.

The O.S. will be written in Rust to prevent most memory security issues and have a good level of abstraction over the programs without compromising performances nor memory usage. The kernel will be a micro-kernel, which will be relatively similar to [Redox's kernel](https://gitlab.redox-os.org/redox-os/kernel).

This also means NightOS will be completely rewritten from scratch. First I'll be writing the high-level documentation about how the system works, as well as some related low-level documents (signals and stuff). Then I'll design the low-level part (how to manage processes efficiently, the memory allocator, etc.), and the implementation will start only when all the designing work is done.

You can find more details about this in the [FAQ](https://github.com/ClementNerma/NightOS/blob/master/docs/FAQ.md#whats-the-currente-state-of-the-project) too.

Feel free to ask me again if you have any other question ;)

**Comment by 8HoLoN** [comment]
Ok, thanks you it was very interresting to read the FAQ and all the stuff. So despite the fact that all the os will be now in rust, is it planned that all the os api will be in js ? (Like batch or Bash for win/linux)

**Comment by ClementNerma** [comment]
No, there will be no support for JavaScript at all. Well, to be exact there is a TypeScript wrapper which is planned for the future (so it will interopable with JavaScript, too). It will be kinda like Electron but optimized for NightOS - so a **lot** lighter, with reduced memory consumption, and direct access to the system's APIs.

**Comment by 8HoLoN** [comment]
OK, that could be cool.
And which processor architecture are you aiming first in your roadmap ? (x86, risc-v, arm, ...)

**Comment by ClementNerma** [comment]
First it will be x86_64 only, then support will be extended to i686 and finally to ARM. Future architectures may be supported later on (like RISC-V or MIPS).

**Comment by ClementNerma** [comment]
First it will be x86_64 only, then support will be extended to i686 and finally to ARM. Future architectures may be supported later on (like RISC-V or MIPS).

But it would already be great if I managed to make it run on a single architecture actually :)

**Comment by ClementNerma** [comment]
You can now find all project-related documentation (roadmap, release schedule, supported architectures...) in [this part of the docs](https://github.com/ClementNerma/NightOS/tree/master/docs/project).
This should answer your question, especially as the documentation grows up, so I close this issue. You can still re-open it if you have additional questions, though ;)

**Comment by ClementNerma** [comment]
You can now find all project-related documentation (roadmap, release schedule, supported architectures...) in [this part of the docs](https://github.com/ClementNerma/NightOS/tree/master/docs/project).
This should answer your question, especially as the documentation grows up, so I close this issue. You can still re-open it if you have additional questions, though ;)
